# Generated by Django 3.2.6 on 2021-08-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDrawings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saveId', models.IntegerField()),
                ('saveName', models.CharField(max_length=500)),
            ],
        ),
    ]
