# Generated by Django 3.2.6 on 2021-08-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawApp', '0002_saveddrawings'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveddrawings',
            name='username',
            field=models.CharField(default='none', max_length=120),
            preserve_default=False,
        ),
    ]
