# Generated by Django 3.2.6 on 2021-08-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawApp', '0003_saveddrawings_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveddrawings',
            name='x1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saveddrawings',
            name='x2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saveddrawings',
            name='y1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saveddrawings',
            name='y2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
