# Generated by Django 3.2.6 on 2021-08-29 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawApp', '0005_saveddrawings_corners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveddrawings',
            name='x1',
        ),
        migrations.RemoveField(
            model_name='saveddrawings',
            name='x2',
        ),
        migrations.RemoveField(
            model_name='saveddrawings',
            name='y1',
        ),
        migrations.RemoveField(
            model_name='saveddrawings',
            name='y2',
        ),
    ]
