# Generated by Django 3.2.6 on 2021-08-29 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawApp', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
