# Generated by Django 3.2.6 on 2021-08-30 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawApp', '0013_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
