# Generated by Django 3.1.13 on 2021-09-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawApp', '0014_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawapp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='saveddrawings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
