# Generated by Django 3.1.13 on 2021-09-03 01:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawApp', '0018_auto_20210902_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddrawings',
            name='corners',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None), size=None),
        ),
    ]
